### ISSUE TITLE
Support for Oruxmaps maybe?

### ISSUE THREAD

**Issue by marksev1** [WebMajstr-/pebble-navigation#5]
Your Pebble app would be very interesting also for hiking use, is there any way you could add support for Oruxmaps which is an excellent android hiking app.

Btw are you maybe from Slovenia (judging by some comments in the code)? And by the nickname :).. Živjo!

**Comment by WebMajstr-** [comment]
Hello,
I agree Oruxmaps is an excellent app for android and I should implement
support for it. I'll try to put it in my schedule and do it, but can't
really promise anything.

Some comments might be in Slovenian, yes ;)

Lep pozdrav / Best regards / Freundliche Grüße,

## WebMajstr :)

If we knew what we were doing, it would not be called research, would it?
(unknown)

**Comment by marksev1** [comment]
Great news, thank you! Lep pozdrav!
